In [40]:
import numpy as np


In [41]:
#creation of array using numpy
arr = np.array([3,2,1])
arr

array([3, 2, 1])

In [42]:
type(arr)

numpy.ndarray

In [43]:
#print Rank 1 array (1 Dimensional array)
arr=np.array([4,5,6])
print(arr)

[4 5 6]


In [44]:
#creating  2d Array
a_list=[[1,2,3],[4,5,6]]
arr2d=np.array([a_list])
print(arr2d)

[[[1 2 3]
  [4 5 6]]]


In [45]:
#creating array with all zeroes
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [46]:
#creating array with all 1s
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [47]:
#changing shape
b.shape=(5,1)#shape of 5 rows and 1 column
print(b)


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [48]:

b=np.linspace(3,9,4)#From 3 to 9 containing 4 elements
print(b)

[3. 5. 7. 9.]


In [49]:
#creating random array
np.random.seed(0)
b=np.random.randint(10,size=6)
print(b)

[5 0 3 3 7 9]


In [50]:
# getting Range of elements
b[0:2]

array([5, 0])

In [28]:
#adding two arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [35]:
#transpose of array
arr=np.array([[1,2,3],
  [4,5,6],
  [7,8,9]])
print(arr.T)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
